// aiflowy-ui-react/src/pages/ai/workflowDesign/components/WorkflowForm.tsx
import React, {useEffect, useState} from "react"
import {Button, Form, Input, Radio, Checkbox, message} from "antd";
import {SendOutlined, UploadOutlined} from "@ant-design/icons";
import {Uploader} from "../../../../components/Uploader";

export type WorkflowFormProps = {
    workflowInfo: any,
    submitLoading: boolean,
    onExecute?: (values: any) => void
}

export const WorkflowForm: React.FC<WorkflowFormProps> = (props) => {

    const {workflowInfo, submitLoading, onExecute} = props
    const [workflowParams, setWorkflowParams] = useState([])

    useEffect(() => {
        setWorkflowParams(workflowInfo?.parameters)
    }, [workflowInfo])

    const onFinish = (values: any) => {
        onExecute && onExecute(values)
    };

    const onFinishFailed = (errorInfo: any) => {
        if (errorInfo.errorFields) {
            message.warning("请完善表单内容")
        } else {
            message.error("失败：" + errorInfo)
        }
    };

    const [paramForm] = Form.useForm();

    const formComponent = (item: any) => {

        const contentType = item.contentType ? item.contentType : "text"

        let checkBoxOptions = []
        if (item.formType === "checkbox") {
            checkBoxOptions = item.enums.map((option: any) => {
                return {
                    label: option,
                    value: option
                }
            })
        }

        return (
            <>
                {contentType === "text" &&
                    <>
                        {item.formType === "input" &&
                            <Input/>
                        }
                        {item.formType === "textarea" &&
                            <Input.TextArea rows={4}/>
                        }
                        {item.formType === "radio" &&
                            <Radio.Group>
                                {item.enums.map((option: any, index: number) => (
                                    <Radio value={option} key={index}>{option}</Radio>
                                ))}
                            </Radio.Group>
                        }
                        {item.formType === "checkbox" &&
                            <Checkbox.Group
                                options={checkBoxOptions}
                            />
                        }
                        {!item.formType &&
                            <Input/>
                        }
                    </>
                }
                {contentType === "other" &&
                    <Input/>
                }
                {
                    (
                        contentType === "image" ||
                        contentType === "video" ||
                        contentType === "audio" ||
                        contentType === "file"
                    ) &&
                    <Uploader
                        maxCount={1}
                        action={'/api/v1/commons/uploadAntd'}
                        children={<Button icon={<UploadOutlined/>}>上传</Button>}
                        onChange={({file}) => {
                            if (file.status === 'done') {
                                let url = file.response?.response.url;
                                if (url.indexOf('http') < 0) {
                                    url = window.location.origin + url;
                                }
                                paramForm.setFieldsValue({
                                    [item.name]: url,
                                });
                            }
                        }}
                    />
                }
            </>
        )
    }

    return (
        <div>
            <Form
                form={paramForm}
                name="basic"
                onFinish={onFinish}
                onFinishFailed={onFinishFailed}
                autoComplete="off"
                layout={"vertical"}
            >
                {workflowParams?.map((item: any, index) => {
                    // console.log(item.contentType + " --> ", item.formType)
                    // formType：radio checkbox input textarea
                    // contentType
                    return (
                        <Form.Item
                            key={index}
                            label={item.formLabel || item.name}
                            name={item.name}
                            rules={[{required: item.required, message: `该项为必填项`}]}
                            extra={item.formDescription}
                        >
                            {formComponent(item)}
                        </Form.Item>
                    )
                })}
                <Form.Item
                    style={{
                        display: "flex",
                        justifyContent: "flex-end",
                    }}
                >
                    <Button disabled={submitLoading} loading={submitLoading} type="primary" htmlType="submit">
                        <SendOutlined/> 开始运行
                    </Button>
                </Form.Item>
            </Form>
        </div>
    )
}

// aiflowy-ui-admin/app/src/views/ai/workflow/components/WorkflowForm.vue
<script setup lang="ts">
import type { FormInstance } from 'element-plus';

import { computed, ref } from 'vue';

import { Position } from '@element-plus/icons-vue';
import {
  ElAlert,
  ElButton,
  ElCheckboxGroup,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElRadioGroup,
  ElSelect,
} from 'element-plus';

import { sse } from '#/api/request';
import { $t } from '#/locales';

export type WorkflowFormProps = {
  onExecuting?: (values: any) => void;
  workflowId: any;
  workflowParams: any;
};
const props = withDefaults(defineProps<WorkflowFormProps>(), {
  onExecuting: () => {
    console.warn('no execute method');
  },
});
const runForm = ref<FormInstance>();
const runParams = ref<any>({});
const submitLoading = ref(false);
const parameters = computed(() => {
  return props.workflowParams.parameters;
});
const { postSse } = sse();
function getContentType(item: any) {
  return item.contentType || 'text';
}
function isResource(contentType: any) {
  return ['audio', 'file', 'image', 'video'].includes(contentType);
}
function getCheckboxOptions(item: any) {
  if (item.enums) {
    return (
      item.enums?.map((option: any) => ({
        label: option,
        value: option,
      })) || []
    );
  }
  return [];
}
function submit() {
  runForm.value?.validate((valid) => {
    if (valid) {
      const data = {
        id: props.workflowId,
        variables: {
          ...runParams.value,
        },
      };

      submitLoading.value = true;
      postSse('/api/v1/aiWorkflow/tryRunningStream', data, {
        onMessage: (message) => {
          if (message.data) {
            const msg = JSON.parse(message.data).content;
            if (msg.status === 'execOnce') {
              ElMessage.warning('流程已执行完毕，请重新发起。');
            } else {
              props.onExecuting?.(message);
            }
          }
        },
        onFinished: () => {
          submitLoading.value = false;
        },
      });
    }
  });
}
</script>

<template>
  <ElForm label-position="top" ref="runForm" :model="runParams">
    <ElFormItem
      v-for="(item, idx) in parameters"
      :prop="item.name"
      :key="idx"
      :label="item.formLabel || item.name"
      :rules="
        item.required
          ? [{ required: true, message: $t('message.required') }]
          : []
      "
    >
      <template v-if="getContentType(item) === 'text'">
        <ElInput
          v-if="item.formType === 'input' || !item.formType"
          v-model="runParams[item.name]"
          :placeholder="item.formPlaceholder"
        />
        <ElSelect
          v-if="item.formType === 'select'"
          v-model="runParams[item.name]"
          :placeholder="item.formPlaceholder"
          :options="getCheckboxOptions(item)"
          clearable
        />
        <ElInput
          v-if="item.formType === 'textarea'"
          v-model="runParams[item.name]"
          :placeholder="item.formPlaceholder"
          :rows="3"
          type="textarea"
        />
        <ElRadioGroup
          v-if="item.formType === 'radio'"
          v-model="runParams[item.name]"
          :options="getCheckboxOptions(item)"
        />
        <ElCheckboxGroup
          v-if="item.formType === 'checkbox'"
          v-model="runParams[item.name]"
          :options="getCheckboxOptions(item)"
        />
      </template>
      <template v-if="getContentType(item) === 'other'">
        <ElInput
          v-model="runParams[item.name]"
          :placeholder="item.formPlaceholder"
        />
      </template>
      <template v-if="isResource(getContentType(item))">
        选择资源组件
      </template>
      <ElAlert v-if="item.formDescription" type="info" style="margin-top: 5px">
        {{ item.formDescription }}
      </ElAlert>
    </ElFormItem>
    <ElFormItem>
      <ElButton
        type="primary"
        @click="submit"
        :loading="submitLoading"
        :icon="Position"
      >
        {{ $t('button.run') }}
      </ElButton>
    </ElFormItem>
  </ElForm>
</template>

<style scoped></style>
